config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show, :create, :destroy] do 
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do 
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    user ||= User.new
    can :read, :all
    return unless user.present?

    can :destroy, Post, author_id: user.id
    can :create, Post
    can :destroy, Comment, author_id: user.id
    return unless user.admin?

    can :destroy, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  after_save :update_comments_counter
  after_destroy :update_comments_counter

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  def update_likes_counter
    likes_counter = post.likes_counter || 0
    post.update(likes_counter: likes_counter + 1)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  after_save :update_posts_counter
  after_destroy :update_posts_counter

  validates :title, presence: true, length: { in: 1..250 }
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id

  before_create :generate_auth_key

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def generate_auth_key
    loop do
      self.auth_key = Devise.friendly_token
      break unless self.class.exists?(auth_key:)
    end
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @comments = Post.find(params[:post_id]).comments.all
    render json: @comments
  end

  def create
    post = Post.find(params[:post_id])
    user = User.find_by(auth_key: request.headers['Auth-Key'])

    if user.present?
      comment = post.comments.build(author: user, text: comment_params[:text])

      if comment.save
        render json: comment, status: :created
      else
        render json: comment.errors, status: :unprocessable_entity
      end
    else
      render json: { error: 'Invalid Auth Key' }, status: :unauthorized
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @posts = User.find(params[:user_id]).posts.all
    render json: @posts
  end

  def show
    @post = Post.find(params[:id])
    render json: @post
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    @users = User.all
    render json: @users
  end

  def show
    @user = User.find(params[:id])
    render json: @user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    text = params[:comment][:text]
    post = Post.find(params[:post_id])
    comment = Comment.new(post:, author: current_user, text:)

    if comment.save
      comment.update_comments_counter
      redirect_to user_post_path(id: post.id), notice: 'Comment added successfully!!'
    else
      flash.now[:alert] = 'Unable to add a comment'
      render :new
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to user_post_path(params[:post_id]), notice: 'Comment deleted successfully!!'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    like = Like.create(post:, author: current_user)
    like.update_likes_counter
    redirect_to user_post_path(id: post.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @author = User.find(params[:user_id])
    @posts = @author.posts.includes(:comments)
    @post = Post.new
  end

  def show
    @author = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    post = current_user.posts.new(post_params)

    if post.save
      redirect_to user_posts_path, notice: 'Post created successfully!!'
    else
      flash.now[:alert] = 'Unable to create a post'
      render :new
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_posts_path(params[:user_id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: @comment, url: user_post_comments_path, method: :post) do |form| %>
  <div>
    <%= form.label :comment %>
    <%= form.text_area :text %>
  </div>
  <%= form.submit "Add comment" %>
<% end %>

app/views/comments/new.html.erb
<%= render "form", comment: @comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <div style="display: flex; flex-direction: column; align-items: flex-end; margin-right: 10px;">
        <%= current_user.name %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete %>
      </div>
    <% end %>
    
    <p class="notice"><%= notice%></p>
    <p class="alert"><%= alert%></p>
    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with(model: @likes,url: user_post_likes_path(@author,@post), method: :post) do |form| %>
  <%= form.submit 'Like' %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: @post, url: user_posts_path, method: :post) do |form| %>
  <div>
    <%= form.label :title%>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <%= form.submit "Create Post" %>
<% end %>

app/views/posts/index.html.erb
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>


<div class='posts-container'>
     <div class='user-image-name-info'>
        <div class='image-container'>
            <img class='user-photo'src=<%= @author.photo%> alt='profile pic'/>
        </div>
        <div class='user'>
            <h2 class='user-name'><%= @author.name%></h2>
            <p class='number-of-posts'>Number of posts: <%= @author.posts_counter%></p>
        </div>
     </div>
     <% if current_user == @author%>
       <%= link_to 'Add a post', new_user_post_path %>
     <%end%>
    <% @posts.each do |post|%>
    <%= link_to user_post_path(@author,post) do%>
        <div class='posts'>
           <div class='post'>
             <h3><%= post.title %></h3>
             <p><%= post.text%></p>
             <span class='comments-likes-info'>Comments:<%= post.comments_counter%>, Likes:<%= post.likes_counter%></span>
            </div>
            <div class='comments'>
              <% post.recent_comments.each do |comment| %> 
                    <p><%= comment.author.name%>: <%= comment.text %></p>
              <% end %>
            </div>
        </div>
        <% end %>
    <% end %>
    <button class='pagination-btn'>Pagination</button>
</div>

<style>
.notice {
    color: green;
}
.posts-container {
    display: flex;
    flex-direction: column; 
    padding: 2%;
    gap:10px
}
.user-image-name-info {
    display:flex;
    gap:2%;
    align-items: center;
    padding: 1% 0
}
.image-container {
    width:200px;
    height:200px;
    border: 1px solid black
  }
.user-photo {
    width:100%;
}
.user {
    width: 100%;
    border: 1px solid black;
    display: flex;
    flex-direction: column;
    justify-content: center;
    padding: 2% 1%;
}
.user-name {
    padding:0;
    margin:0;
    font-size: 2.5rem;
}
.number-of-posts {
    text-align: end;
    font-size: 1.3rem;
    padding:0;
    margin:0;
}
.post, .comments {
    border: 1px solid black;
    padding: 1%
}
.post {
    display: flex;
    flex-direction: column;
}
.comments-likes-info {
    align-self: end;
}
.pagination-btn {
    align-self: center;
    font-size: 1.2rem
}
</style >

app/views/posts/new.html.erb
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class='post-detail'>
    <div class='post'>
       <div class='post-header-container'>
          <h3 class='post-header-text'><%= @post.title %> by <%= @author.name %></h3> 
          <span class='comments-likes-info'>Comments:<%= @post.comments_counter%>, Likes:<%= @post.likes_counter%></span>
       </div>
        <p><%= @post.text%></p>
    </div>
    <div class='comments'>
        <% @post.comments.each do |comment| %> 
            <p><%= comment.author.name%>: <%= comment.text %></p>
            <% if can? :destroy, comment %>
        <%= button_to 'Delete comment', user_post_comment_path(@author, @post, comment), method: :delete%>
    <% end %>
        <% end %>
    </div>
    <%= link_to 'Add a comment', new_user_post_comment_path(@author.id,@post.id) %>
    <%= render '/likes/form'%>
    <% if can? :destroy, @post %>
        <%= button_to 'Delete post', user_post_path(@author, @post), method: :delete%>
    <% end %>
</div>

<style>
.notice {
    color: green;
}
.post-detail {
    display: flex;
    flex-direction: column; 
    padding: 2%;
    gap:10px
}

.post, .comments {
    border: 1px solid black;
    padding: 1%
}
.post-header-container {
    display: flex;
    align-items: center;
    justify-content: space-between;
}
.post-header-text {
    font-size: 2.5rem;
}
.comments-likes-info {
    font-size: 1.3rem;
}
</style >

app/views/users/index.html.erb
<% @users.each do |user| %> 
   <%= link_to user_path(user.id) do %>
    <div class='users'>
        <div class='image-container'>
          <img class='user-photo' src='<%= user.photo%>' alt='profile pic'/>
        </div>
        <div class='user'>
          <h3 class='user-name'><%= user.name %></h3>
          <span class='number-of-posts'>Number of posts: <%= user.posts_counter %></span>
        </div>
    </div>
    <% end %>
<% end %>

<style>
.users {
    display:flex;
    gap:2%;
    align-items: center;
    padding: 1% 0
}
.image-container {
  width: 200px;
  height: 200px;
  border: 1px solid black
  }
.user-photo {
  width:
}
.user{
  width: 100%;
  border: 1px solid black;
  display: flex;
  flex-direction: column;
  justify-content: center;
  padding: 2% 1%

}
.user-name {
  padding:0;
  margin:0;
  font-size: 2.5rem;
}
.number-of-posts{
  align-self: end;
  font-size: 1.3rem;
}
</style >

app/views/users/show.html.erb
<div class='user-detail'>
     <div class='user-image-name-info'>
        <div class='image-container'>
            <img class='user-photo'src='' alt='profile pic'/>
        </div>
        <div class='user'>
            <h2 class='user-name'><%= @user.name%></h2>
            <span class='number-of-posts'>Number of posts: <%= @user.posts_counter%></span>
        </div>
     </div>
    <div class='bio'>
      <h3>Bio</h3>
      <p><%= @user.bio%></p>
    </div>
        <div class='posts'>
            <% @user.recent_posts.each do |post|%>
                <%= link_to user_post_path(@user,post) do%>
                    <div class='post'>
                        <h3><%= post.title%></h3>
                        <p><%= post.text%></p>
                    </div>
                <% end %>
            <% end %>
        </div>
    <%= link_to 'See all posts', user_posts_path(@user) %>

</div>

<style>
.user-detail {
    display: flex;
    flex-direction: column; 
    padding: 2%;
    gap:10px
}
.user-image-name-info {
    display:flex;
    gap:2%;
    align-items: center;
    padding: 1% 0
}
.image-container {
    width: 200px;
    height: 200px;
    border: 1px solid black
  }
.user-photo {
    width:100%;
}
.user{
    width: 100%;
    border: 1px solid black;
    display: flex;
    flex-direction: column;
    justify-content: center;
    padding: 2% 1%;

}
.user-name {
    padding:0;
    margin:0;
    font-size: 2.5rem;
}

.number-of-posts{
    align-self: end;
    font-size: 1.3rem;
    padding:0;
    margin:0;
}
.bio,.post{
    border: 1px solid black;
    padding: 1%
}
</style >